version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=DB_Destored
      - POSTGRES_USER=destoredUser
      - POSTGRES_PASSWORD=destored123
    ports:
      - 5432:5432
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=lgmassa98@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

